// DELF Configuration
// Generated from top_200_exam_universe_seed.csv

export const EXAM_CONFIG = {
  examId: "EXAM021",
  slug: "delf",
  name: "DELF",
  fullName: "DELF",
  alias: "DELF",
  family: "DELF",
  category: "Language proficiency",
  subcategory: "French proficiency",
  country: "Global",
  region: "Global",
  languages: ["French"],
  estimatedAnnualTakers: "varies",
  testingWindow: "Scheduled sessions",
  schedulePattern: "Multiple sessions/year",
  ageGroup: "12-40",
  targetUser: "Language learner",
  delivery: "Paper/computer mixed by center",
  questionTypes: ["Listening","reading","writing","speaking"],
  adaptivity: "Linear",
  sections: "Level-specific",
  scoringMode: "Pass/fail score",
  essayOrSpeaking: "Speaking + writing",
  ipRisk: "Medium",
  contentReuse: "language_4skills",
  uiEngine: "4skills_cefr",
  monetizationPotential: "Medium",
  tier: "Tier 3",
  launchWave: "Wave 5",
  themeColor: "#059669",
  themeColorDark: "#047857",
  localizationComplexity: "Medium",
  offlineNeeded: false,
  mobileFirst: false,
  locale: "fr",
  isRTL: false,
  freemiumGate: {
    dailyQuestions: 10,
  },
} as const;

export type ExamConfig = typeof EXAM_CONFIG;
